export const topics = [
  {name: 'Documentation', estimation: 0},
  {name: 'Localisation', estimation: 0},
  {name: 'Legality', estimation: 0},
  {name: 'Security', estimation: 0},
  {name: 'Integration to the current system', estimation: 0},
  {name: 'Implementation of the code', estimation: 0},
  {name: 'Exception management', estimation: 0},
  {name: 'Unit tests', estimation: 0},
  {name: 'Integration tests', estimation: 0},
  {name: 'e2e tests', estimation: 0},
  {name: 'Manuel tests', estimation: 0},
  {name: 'Code review', estimation: 0},
  {name: 'Log Events', estimation: 0},
  {name: 'Metrics', estimation: 0},
  {name: 'Alarm', estimation: 0},
  {name: 'Tracing', estimation: 0},
  {name: 'Performance', estimation: 0},
  {name: 'Package', estimation: 0},
  {name: 'Deployment', estimation: 0},
  {name: 'UX', estimation: 0},
  {name: 'UI', estimation: 0},
  {name: 'Accessibility', estimation: 0},
];
